name: Docker Image CI for GHCR

on: [push]

jobs: 
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the image
              run: |
                    docker login --username shivamklr --password ${{ secrets.GH_ACCESS_TOKEN}} ghcr.io
                    docker build . -t ghcr.io/shivamklr/solana-anchor-bun:latest
                    docker push ghcr.io/shivamklr/solana-anchor-bun:latest


